# FROM node:20-alpine

# COPY package*.json ./
# RUN npm ci 
# USER node

# WORKDIR /home/node/

# COPY . .

# RUN npm run build 
# EXPOSE 8000

# CMD [ "npm", "start" ]

FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

EXPOSE 8000

ARG PROJECT_Name

ARG BACK_PORT
ARG BACK_MONGODB_URI
ARG BACK_MONGODB_NAME

ARG STATIC
ARG LOGS

ARG BACK_SECRET

ARG BACK_EmailHost
ARG BACK_EmailPort

ARG BACK_EmailUser
ARG BACK_EmailPass

ARG DEV_Email

ARG NODE_ENV
ARG MAIN_URL

ARG CLOUDINARY_CLOUD_NAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET

ARG REDIS_HOST
ARG REDIS_PORT
ARG REDIST_PASSWORD

ENV PROJECT_Name=$PROJECT_Name
ENV BACK_PORT=$BACK_PORT
ENV BACK_MONGODB_URI=$BACK_MONGODB_URI
ENV BACK_MONGODB_NAME=$BACK_MONGODB_NAME
ENV STATIC=$STATIC
ENV LOGS=$LOGS
ENV BACK_SECRET=$BACK_SECRET
ENV BACK_EmailHost=$BACK_EmailHost
ENV BACK_EmailPort=$BACK_EmailPort
ENV BACK_EmailUser=$BACK_EmailUser
ENV BACK_EmailPass=$BACK_EmailPass
ENV DEV_Email=$DEV_Email
ENV NODE_ENV=$NODE_ENV
ENV MAIN_URL=$MAIN_URL
ENV CLOUDINARY_CLOUD_NAME=$CLOUDINARY_CLOUD_NAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET=$CLOUDINARY_API_SECRET
ENV REDIS_HOST=$REDIS_HOST
ENV REDIS_PORT=$REDIS_PORT
ENV REDIST_PASSWORD=$REDIST_PASSWORD

CMD [ "npm", "run", "dev" ]